version: "3.7"
services:
 php:
  image: app-php:0.0.1
  build:
   context: ./docker
   dockerfile: php
  depends_on:
   - db
  ports:
   - "80:80"
  networks:
   - app-net
 db:
  image: sntnl-db:0.0.1
  command: --default-authentication-plugin=mysql_native_password
  hostname: app-db
  build:
   context: ./docker
   dockerfile: mysql
  ports:
   - "3306:3306"
  networks:
   - app-net
networks:
 app-net:
